# Generated by Django 4.2.4 on 2023-08-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funchash', '0004_remove_documento_conteudo_documento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='conteudo_hash',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
