# Generated by Django 4.2.4 on 2023-08-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funchash', '0005_documento_conteudo_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('assinatura', models.CharField(max_length=200)),
            ],
        ),
    ]
