# Generated by Django 4.2.4 on 2023-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funchash', '0006_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_anexo',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-30 15:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
