# Generated by Django 4.2.4 on 2023-09-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funchash', '0007_documento_data_anexo_documento_data_assinatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nome',
        ),
    ]
